version: 2.1
jobs:
  setup:
    machine: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install saucectl && export PATH=$PATH:~/app/node_modules/saucectl/bin
      - persist_to_workspace:
          root: ~/app
          paths:
            - .

  # Cypress Example
  test-cypress:
    working_directory: ~/app
    docker:
      - image: node:10.12
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Cypress Tests
          command: |
            saucectl run -c ./.sauce/cypress.yml
          environment:
            BUILD_ID: $CIRCLE_BUILD_NUM
            BUILD_ENV: CircleCI

workflows:
  version: 2
  default_workflow:
    jobs:
      - setup
      - test-cypress:
          requires:
            - setup