version: 2.1
jobs:
  setup:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.12
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install saucectl
      - persist_to_workspace:
          root: ~/app
          paths:
            - .
 # Cypress Example
  test-cypress:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.12
    steps:
      - attach_workspace:
          at: ~/app
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Cypress Tests
          command: |
            chmod -R 777 ./tests && ~/app/node_modules/.bin/saucectl run -c ./.sauce/cypress.yml
          environment:
            BUILD_ID: $CIRCLE_BUILD_NUM
            BUILD_ENV: CircleCI
      

workflows:
  version: 2
  default_workflow:
    jobs:
      - setup
      - test-cypress:
          requires:
            - setup